# Generated by Django 5.1.4 on 2024-12-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('cid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=10)),
                ('tname', models.CharField(max_length=10)),
            ],
        ),
    ]
